---
tags: []
projects: []
---
:spring_version: current
:spring_boot_version: 1.5.9.RELEASE
:Controller: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Controller.html
:DispatcherServlet: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/servlet/DispatcherServlet.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:ResponseBody: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/ResponseBody.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-cloudant
This guide walks you through the process of creating a Spring application that connects to a Cloudant instance.

== What you'll build

You'll build a Spring application that stores and retrieves greetings from a Cloudant database.


== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]



[[initial]]

== Set up a Cloudant instance

To complete this guide you will need an accessible Cloudant instance.

To use an instance on IBM Cloud:

. Create an account or log in to http://bluemix.net[IBM Cloud]
. Create a https://console.bluemix.net/docs/services/Cloudant/tutorials/create_service.html#creating-a-cloudant-nosql-db-instance-on-ibm-cloud[Cloudant instance] in your dashboard

To create a local instance in a Docker container:

. Use the Cloudant developer image on https://hub.docker.com/r/ibmcom/cloudant-developer/[Dockerhub]
. Follow the instructions on Dockerhub but supply a port different to `8080` since Spring uses `8080` by default.

== Create an application properties file

Create an application properties file with `cloudant.url`, `cloudant.username` and `cloudant.password` set to the url, username and password of your Cloudant instance and `cloudant.db` set to `greeting`.

Note: Refer to the IBM Cloud or Dockerhub documentation to determine the `cloudant.url`, `cloudant.username` and `cloudant.password` for your Cloudant instance.

`src/main/resources/application.propertes`
----
include::complete/src/main/resources/application.properties
----

== Create a greeting model

Create a class to represent a greeting object:

`src/main/java/hello/Greeeting.java`
[source,java]
----
include::complete/src/main/java/hello/Greeting.java[]
----

The `_id` and `_rev` fields are required by Cloudant. The model also includes a `content` field to store the contents of the greeting.

== Create a resource controller

Create a new controller for your Spring application:

`src/main/java/hello/GreetingController.java`
[source,java]
----
include::complete/src/main/java/hello/GreetingController.java[]
----

The `Database` object that is auto-wired into your controller allows you to connect to the database called `greeting` in your Cloudant instance.

This example includes a `GET` endpoint to list all stored greetings, a `GET` endpoint for a specific greeting, a `POST` endpoint for adding greetings and a `DELETE` endpoint for deleting greetings.


== Make the application executable

Although it is possible to package this service as a traditional link:/understanding/WAR[WAR] file for deployment to an external application server, the simpler approach demonstrated below creates a standalone application. You package everything in a single, executable JAR file, driven by a good old Java `main()` method. Along the way, you use Spring's support for embedding the link:/understanding/Tomcat[Tomcat] servlet container as the HTTP runtime, instead of deploying to an external instance.


`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-application.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]


Logging output is displayed. The service should be up and running within a few seconds.


== Test the application

Now that the application is running, you can test it. Go to http://localhost:8080/greeting to see a list of greetings.

To add a new greeting run following curl command:

[subs="attributes", role="has-copy-button"]
....
curl -d '{"content":"Hello, this is a greeting!"}' -H "Content-Type: application/json" -X POST http://localhost:8080/greeting
....

Once you have a greeting in the database you can get the greeting at http://localhost:8080/greeting/{id}


== Summary

Congratulations! You've just developed a Spring application that uses Cloudant! 




include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]

